[package]
name = "magical-bitcoin-wallet"
version = "0.1.0"
edition = "2018"
authors = ["Riccardo Casatta <riccardo@casatta.it>", "Alekos Filini <alekos.filini@gmail.com>"]

[dependencies]
log = "^0.4"
bitcoin = { version = "0.23", features = ["use-serde"] }
miniscript = { version = "0.12" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
base64 = "^0.11"
async-trait = "0.1"

# Optional dependencies
sled = { version = "0.31.0", optional = true }
electrum-client = { version = "0.1.0-beta.6", optional = true }
reqwest = { version = "0.10", optional = true, features = ["json"] }
tokio = { version = "0.2", optional = true, features = ["rt-core"] }
futures = { version = "0.3", optional = true }
clap = { version = "2.33", optional = true }

[features]
minimal = []
compiler = ["miniscript/compiler"]
default = ["key-value-db", "electrum"]
electrum = ["electrum-client"]
esplora = ["reqwest", "futures", "tokio"]
key-value-db = ["sled"]
cli-utils = ["clap"]

[dev-dependencies]
lazy_static = "1.4"
rustyline = "6.0"
dirs = "2.0"
env_logger = "0.7"
rand = "0.7"

[[example]]
name = "repl"
required-features = ["cli-utils"]
[[example]]
name = "psbt"
[[example]]
name = "parse_descriptor"

[[example]]
name = "miniscriptc"
path = "examples/compiler.rs"
required-features = ["compiler"]

# Provide a more user-friendly alias for the REPL
[[example]]
name = "magic"
path = "examples/repl.rs"
required-features = ["cli-utils"]

